language: java
jdk:
  - oraclejdk8
  - openjdk8

before_install:
 - chmod +x gradlew

install: ./gradlew setupciworkspace -S
script: ./gradlew build -S

branches:
  only:
  - master
  
deploy:
  provider: releases
  api_key:
    secure: $api_key
  file: "build/libs/SuperheroesAddon-1.1.jar"
  name: "SuperheroesAddon-$modversion"
  skip_cleanup: true